### ISSUE TITLE
Get inspection reference from any task?

### ISSUE THREAD

**Issue by autt** [equinor/isar#147]
**Describe the improvement you would like to see**
Today, inspection references are retrieved from the current task. 

` def get_inspection_references(self, current_task: Task) -> Sequence[Inspection]: `

Does it have to be only the current task that we get inspection references from?

From discussion in PR #114 :

@tsundvoll: Does it have to be the current task we want to get the inspection reference from? Could this instead be renamed to just task? This is maybe a separate PR; but still an interesting thought.

@aestene: Good idea. It would change the requirements to the implementation of the robot though depending on what the robot does.
For example, would we expect to retrieve inspections for "any" task id? I would assume just for the task IDs in the current mission.

**How will this change existing functionality?**
This will enable the option of retrieving inspection references from other tasks than just the current task. 

**How will this improvement affect the current Threat Model?**
This should not affect the Threat Model.

**Comment by vetlek** [comment]
This issue can be closed due to `get_inspection_references` being removed from the robot interface in #167
