### ISSUE TITLE
Add backoff strategy for MQTT broker

### ISSUE THREAD

**Issue by aestene** [equinor/isar#198]
**Describe the improvement you would like to see**
The broker connection should retry connection a certain amount of times before giving up. The suggested strategy is to use backoff intervals which tries several times like [1s, 5s, 20s, 60s, 180s] etc.

**How will this change existing functionality?**
Will make the robot try to reconnect if the broker connection is unavailable.

**How will this improvement affect the current Threat Model?**
N/A

**Comment by vetlek** [comment]
I think this is automatically done when using the paho.mqtt.client
