### ISSUE TITLE
Move geometry models to Alitra

### ISSUE THREAD

**Issue by aestene** [equinor/isar#205]
**Describe the improvement you would like to see**
The models for geometry (`Position`, `Orientation` and `Pose`) could be a part of Alitra instead of ISAR. Then the casting between Alitra specific objects and ISAR specific objects in the transformation would not be necessary. Downside is that robot repositories would have to import the definitions from Alitra.

**How will this change existing functionality?**
Would have to move model definitions to Alitra, create new release and change imports for all relevant repositories.

**How will this improvement affect the current Threat Model?**
NA

**Comment by Christdej** [comment]
I like the idea. In ALITRA we have: 
`Point` which is almost the same as `Position`
`Translation` which is almost the same as `Orientation`
And importing the these classes from alitra makes more sense imo.
