### ISSUE TITLE
Load poses from file

### ISSUE THREAD

**Issue by Christdej** [equinor/isar#240]
**Describe the new feature you would like to see**
Being able to load poses from file, for instance json. And move predefined_poses.py to a file. Some functionality might have to be implemented in alitra.

**Describe the solution you'd like**
load poses from file, such that we can remove predefined_poses.py or atleast reduce the length of the file.

**How will this feature affect the current Threat Model?**
It doesnt

**Comment by aestene** [comment]
Is this necessary? The solution with predefined poses is meant to be a temporary fix which we would like to get rid off. As such there isn't much difference in writing it directly into a python file or into a json which is then read through a python script?

**Comment by aestene** [comment]
I agree that it's  along file which is not really maintained we just add on things to it as we need them. Splitting into multiple files would be nice as we could then have separate files for separate assets.

If we want to store them outside the repo etc. there is quite a lot of work for setting this up in a specific manner for a solution which is supposed to be a workaround and temporary. I see that it will stick around for a bit longer though so I'm not against the idea only if it's worth the effort.

**Comment by Christdej** [comment]
How temporary are we talking here? I would maybe argue that if it is staying for an extended amount of time atleast dividing the file into several file could be worth the effort.
