### ISSUE TITLE
Modularize planning functionality for selecting next task

### ISSUE THREAD

**Issue by aestene** [equinor/isar#261]
**Describe the new feature you would like to see**
The next task in a mission is today always chosen as the next element in the list using an iterator. However, it would be a nice feature to be able to modularize this functionality behind an interface such that different types of planners could be implemented. This would allow us to have planners that select the next task on other criteria, for example distance to location, battery level etc.

**Describe the solution you'd like**
Utilize the existing setup for the current implementation of the `MissionPlannerInterface` and the `StorageInterface` to implement a new interface. A suggestion would be to rename the old `MissionPlanner` to `MissionLoader` and use `Planner` in this setting instead as it's conceptually more correct.

The interface would implement one function something like this
```
def select_next_task(tasks: List[Task]) -> Task:
```
Where the interface is passed the list of tasks in the current mission and returns which task should be performed next.

**How will this feature affect the current Threat Model?**
N/A

**Comment by MortFred** [comment]
Blocked by vacation
