### ISSUE TITLE
Using latest uvicorn version does not work

### ISSUE THREAD

**Issue by knord94** [equinor/isar#291]
Installing ISAR with the latest uvicorn version does not work. "Missing module: uvicorn.logging not found"
Workaround with specifying version 0.17.6.

**Comment by MortFred** [comment]
Check this week?

**Comment by MortFred** [comment]
We are running latest version of Uvicorn, and everything works fine now. No action needed.

**Comment by GodVenn** [comment]
Thank you for closing this
