### ISSUE TITLE
Running Isar in docker does not publish MQTT battery correctly

### ISSUE THREAD

**Issue by MortFred** [equinor/isar#302]
**Describe the bug**
Battery is not updated correctlyin backend model through MQTT when Isar is running in docker. 

**To Reproduce**
1. Run Flotilla (in docker when we tested)
2. Run Isar in docker
3. Open frontend

**Expected behavior**
Battery status should stay at default 95.2

**Comment by MortFred** [comment]
Sondre had a suggestion; the battery publishing from isar_robot has not been commited to isar_robot upstream repository.
Merging these changes will probably fix this issue

**Comment by GodVenn** [comment]
Change merged to isar-robot
