### ISSUE TITLE
Handle access restrictions 

### ISSUE THREAD

**Issue by anetteu** [equinor/isar#320]
**Describe the improvement you would like to see**
Make sure that only the required user groups have access to ISAR

**How will this change existing functionality?**
A clear and concise description on how this will affect current functionality.

**How will this improvement affect the current Threat Model?**
Should improve threat model by restricting access to the required groups only

**Comment by GodVenn** [comment]
ISAR was only checking Authentication, not Authorization. 
Made a new issue to handle this #348
