### ISSUE TITLE
ISAR MQTT without SSL/TLS

### ISSUE THREAD

**Issue by luteberget** [equinor/isar#323]
**Describe the new feature you would like to see**
I run mosquitto/mqtt locally without SSL/TLS setup. Need to comment out these lines in `src/isar/services/service_connections/mqtt/mqtt_client.py` line 45:
```
        #cert_path = os.path.join(dirname, "../../../config/certs/ca-cert.pem")
        #self.client.tls_set(ca_certs=cert_path) 
```

**Describe the solution you'd like**
Maybe TLS could be disabled with a setting?

**How will this feature affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by aestene** [comment]
I agree that there should be an option to enable/disable the certificate authentication on MQTT. The solution will be as simple as adding a setting variable and using that in the line you mention to turn on and off the authentication.

We will add it to our backlog but feel free to submit a pull request if you wish.
