### ISSUE TITLE
Empty response body on OK request in scheduling controller

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/isar#351]
**Describe the bug**
Pause-, resume- and stop mission endpoints in scheduling controller returns "null" in response body for response 200. Mission is successfully pause, stopped or resumed, but the backend throws an error because of the empty response body.

**To Reproduce**
Schedule a mission in frontend -> pause, resume or stop mission and see error messages.

**Expected behavior**
Scheduling api should not return an empty response body on successful stop, pause or resume.

**Screenshots**
![image](https://user-images.githubusercontent.com/66949993/196709699-c588a78f-edbb-4eb9-847c-f6f5eeb01f83.png)

**Comment by GodVenn** [comment]
![image](https://user-images.githubusercontent.com/57716654/196712021-0aef370f-5bb5-4268-8dc4-67d8d69a0a67.png)
This code should be changed so that an empty string is accepted if that is the case

**Comment by GodVenn** [comment]
![image](https://user-images.githubusercontent.com/57716654/196712412-03adce2c-eb98-4296-b37c-626cca8e0c40.png)
This code has been copy pasted from the "Start-Mission" endpoint to the others.
That is the reason for the bug; the other endpoints should not expect to get a mission response from ISAR.
