### ISSUE TITLE
Add desired analysis method as metadata for inspection

### ISSUE THREAD

**Issue by aestene** [equinor/isar#384]
**Describe the new feature you would like to see**
A new inspection should have an optional metadata field which includes which inspection analysis should be run on this piece of data. It might be manually specified for now but in the future can come as input through the mission plan.

**Describe the solution you'd like**
Metadata includes desired analysis to run. This might be multiple methods.

In the beginning there should be a way to specify which analysis methods on ISAR level as this is not ready from the Echo planner yet. This can be a simple workaround as setting all options for an image and gas detection for a thermal video or similar. 

**How will this feature affect the current Threat Model?**
N/A

**Comment by oysand** [comment]
See #385

**Comment by GodVenn** [comment]
Closed with PR #400
