### ISSUE TITLE
Add index indicating execution order of IsarTasks and IsarSteps in missions

### ISSUE THREAD

**Issue by phhuseboe** [equinor/isar#413]
**Describe the improvement you would like to see**
Add index indicating execution order of IsarTasks and IsarSteps in missions

**How will this change existing functionality?**
The order in which every task is executed in a mission will be explicitely stated, making it easier to keep track and use of tasks order through the pipeline (Flotilla -> ISAR -> Flotilla)

**How will this improvement affect the current Threat Model?**

**Comment by GodVenn** [comment]
Closed by https://github.com/equinor/flotilla/pull/664
