### ISSUE TITLE
Switch state_machine track in idle state

### ISSUE THREAD

**Issue by GodVenn** [equinor/isar#416]
**Describe the new feature you would like to see**
An optional path in the state machine will be to start a full mission on a robot, taking advantage of the supplier's mission system.

The settings for a robot will define what path it should take.
Based on this, the state machine will do the "Mission Path" or the "Idle Path" and use either `initiate_mission` or `initiate_step`.
If attempting an unsupported path, `initiate_mission`/`initiate_step` will throw a `NotImplementedError`.
This needs handling. It should be treated as a critical error crashing the application as the error is related to the config.

**How will this feature affect the current Threat Model?**
N/A

**Comment by Christdej** [comment]
Fixed
