### ISSUE TITLE
Raise Warning if loaded maps are overlapping

### ISSUE THREAD

**Issue by Christdej** [equinor/isar#443]
**Describe the improvement you would like to see**
Raise a Warning if any of the maps are overlapping in any way

**How will this change existing functionality?**
Will make debugging easier because when maps are overlapping, creating a mission in robots might fail and we get few indicators why that might be.

**Comment by tsundvoll** [comment]
Or simply terminate with a describing message of what happened

**Comment by aestene** [comment]
Closed and reopened in another repository.
