### ISSUE TITLE
Initiate mission keeps retrying if Initiate Infeasible for full missions

### ISSUE THREAD

**Issue by Afonso-2403** [equinor/isar#521]
**Describe the bug**
When a initiating a mission for a robot that does not run stepwise, if it raises a `RobotInfeasibleMissionException` isar keeps retrying to send the mission infinitely.
 
**To Reproduce**
Connect isar to a robot package that runs full missions and trigger a `RobotInfeasibleMissionException` from that package

**Expected behavior**
Initiate mission should fail and the robot should go back to idle

**Comment by andchiind** [comment]
Fixed in #522
