### ISSUE TITLE
Have ISAR state represent and report robot status

### ISSUE THREAD

**Issue by oysand** [equinor/isar#532]
**Describe the improvement you would like to see**
The robot status reported from isar should be based on the state.

**How will this change existing functionality?**
To represent the robot status the isar state needs to also represent Offline and Blocked

- [x] Introduce Offline state

- [ ] Introduce Blocked state

**How will this improvement affect the current Threat Model?**
N/A

**Comment by tsundvoll** [comment]
Blocked state not deemed necessary for current solution. We can consider adding it later if still needed
