### ISSUE TITLE
Missions abort after successful localisation, reporting failed localisation

### ISSUE THREAD

**Issue by haakonsf** [equinor/isar#575]
**Describe the bug**
When scheduling in dev the missions are all aborted due to failing localisation. The localisation mission reports back as successful. 

**To Reproduce**
Queue all missions on a deck

**Expected behavior**
The missions run as normal after the successful localisation.

**Screenshots**

**Comment by andchiind** [comment]
Explained in more detail in [#1655](https://github.com/equinor/flotilla/issues/1655)
