### ISSUE TITLE
ISAR should only focus on Tasks. Steps should be delegated to the translational layers

### ISSUE THREAD

**Issue by oysand** [equinor/isar#612]
**Describe the improvement you would like to see**
ISAR should only need to focus on Tasks and does not need to look at Steps. This way a lot of the functionality currently handled as steps should be handled as task.

**How will this change existing functionality?**

1. Differentiating types such as MotionStep and InspectionStep should be assigned to tasks instead.
2. The robot interface should be updated so that status is only requested for tasks. Meaning that mission_status and step_status can be combined to one status call that gives the status for all the tasks.

**How will this improvement affect the current Threat Model?**
N/A

**Comment by tsundvoll** [comment]
To be discussed if the time to do this is now, or later. Depends on the ability to test it now.

**Comment by tsundvoll** [comment]
ISAR steps ™  is removed https://github.com/equinor/isar/pull/617

**Comment by tsundvoll** [comment]
ISAR steps ™ is removed https://github.com/equinor/isar/pull/617
