### ISSUE TITLE
ISAR crashed when DriveToSafePosition mission started

### ISSUE THREAD

**Issue by Eddasol** [equinor/isar#621]
**Describe the bug**
When the ongoing mission described here -> https://github.com/equinor/flotilla/issues/1758 completed and the DriveToSafePosition mission started, ISAR crashed.

The area the robot was running in had only one safe position. This safe position was an infeasible point.

**To Reproduce**

**Expected behavior**
Should fail, and not crash

**Screenshots**
![Image](https://github.com/user-attachments/assets/ebd248e2-04f1-401e-aa82-dcdbc9f35ff8)

**Comment by tsundvoll** [comment]
Investigate more the root cause

**Comment by Eddasol** [comment]
Should be solved by step to task rewrite
