### ISSUE TITLE
Add default map implementation

### ISSUE THREAD

**Issue by aestene** [equinor/isar#63]
The current default map implementation uses a very particular map that will not make sense to new users. Suggestion is to add a default map where the robot and asset frame have the same base coordinate system. Thus there will be a simple default implementation.

A new map must be added to [this folder](https://github.com/equinor/isar/tree/main/src/isar/config/maps).

The default map configuration variable [here](https://github.com/equinor/isar/blob/main/src/isar/config/default.ini) should be changed to use the new map.

**Comment by autt** [comment]
Resolved by #79
