### ISSUE TITLE
Add unique IDs to every step

### ISSUE THREAD

**Issue by aestene** [equinor/isar#96]
Add a unique ID to every step in a mission. The ID can then be used to manage inspections within isar-robot such that ISAR itself only has to manage the step ID.

This will remove the need for `vendor_mission_id` where this is present.

**Comment by aestene** [comment]
ID hierarchy: 
![image](https://user-images.githubusercontent.com/14331473/143557712-ef42e6ee-8051-4823-8ea6-337e230369fa.png)

**Comment by aestene** [comment]
Mission, step, inspection hierarchy: 
![image](https://user-images.githubusercontent.com/14331473/143557768-0a59f730-a7db-410e-90d4-1017f82c320f.png)

**Comment by autt** [comment]
Mission, Task, Inspection is left to #146
